### ISSUE TITLE
[I] Совместимость с другими плагинами

### ISSUE THREAD

**Issue by BlackYuzia** [SB-MaterialAdmin/NewServer#1]
Может ли разраб, который делал этот плагин.
Сделать более лучшую совместимость с другим плагином который он делал.  (Супер админка) либо сделать отдельную тестовую ветку в которой будет помещен плагин:  МA и Супер Админка. 

Если это возможно конечно :)

**Comment by BlackYuzia** [comment]
If you can`t translate. That good :)

**Comment by Grey-rus** [comment]
В чём выражается не совместимость двух этих плагинов?

**Comment by BlackYuzia** [comment]
@Grey-rus в баговании меню.
а именно: Залазит одно на другое.
При рестарте плагина MA (и/или) СА (Супер Админка)

Конечно, рестартать СА (релоадить) нельзя, вроде.
Но бывают случаи что приходиться релоадить МА, а он, в свою очередь, жрет пункт СА-шника, и вместо СА, открывается МА, т.е. 2 пункта = МА.
Хоть названия и:
- Супер Админка
- Управление Блокировками

**Comment by BlackYuzia** [comment]
По этому, подумал, почему бы не сделать отдельную ветку где уже будет встроен плагин СА в МА?

**Comment by BlackYuzia** [comment]
Что бы они "дружили" :d

**Comment by Grey-rus** [comment]
Лучше смени карту или перезагрузить сервер. С этим ни чего не сделаешь особенность создание меню в са(из-за флагов доступа к меню). Но подумаю на досуге, может что нибудь да можно сделать.

**Comment by BlackYuzia** [comment]
@Grey-rus вроде после смены карты (вроде) не фиксится. Только после рестарта.

**Comment by Grey-rus** [comment]
Можешь написать что за случаи что нужно так вот плагин перезагрузить?

**Comment by BlackYuzia** [comment]
@Grey-rus 

> sm plugins reload materialadmin
> sm_reloadadmins

Иногда админы слетают (не знаю почему, тупо БАЦ и нет ни у кого на сервере админки)
Спасает только релоад плагина.

Я уже кидал логи через Крузю вроде, по этому поводу. 

> PS:Архив,а в архиве архивы и в каждом архиве лог :DD

**Comment by Grey-rus** [comment]
Про слетание админки я не знаю почему  так, нужно быть во время этого на севрере и выполнять тесты, чтоб понять точно что не так, и для этого ещё нужно написать плагин для тестов.
Про поломку меню, это скорее какой-то плагин ломает её. (это если перезагружается какой то плагин который интегрируется в меню или другие могут быть причины.)

**Comment by Grey-rus** [comment]
Как в плагине это решить не знаю, но есть простое решение, выполнить так перезагрузку плагинов
`sm plugins reload materialadmin;sm plugins reload ma_adminmenu;sm plugins reload super_adminka` это если со изменённым админ меню, для стандартного админ меню `sm plugins reload materialadmin;sm plugins reload adminmenu;sm plugins reload super_adminka`.
И после этого надо перезайти, для того чтоб админ права были.

**Comment by BlackYuzia** [comment]
@Grey-rus Я конечно все понимаю но это же  *КОСТЫЛЬ** :d 
И ладно если бы маленький. Но тут это просто **КОСТЫЛИЩЕ**

**Comment by Grey-rus** [comment]
Это не костыль, просто последовательная перезагрузка плагинов.
