### ISSUE TITLE
Ошибка при перезапуске плагина

### ISSUE THREAD

**Issue by GameFenix** [SB-MaterialAdmin/NewServer#104]
Здравствуйте,после выполнения команды sm plugins reload sb/materialadmin.smx
Возникает следующая ошибка: 
```
L 06/11/2020 - 10:12:56: [SM] Exception reported: Native is not bound
L 06/11/2020 - 10:12:56: [SM] Blaming: sb/ma_adminmenu.smx
L 06/11/2020 - 10:12:56: [SM] Call stack trace:
L 06/11/2020 - 10:12:56: [SM]   [0] MAGetConfigSetting
L 06/11/2020 - 10:12:56: [SM]   [1] Line 90, ma_adminmenu.sp::MAOnConfigSetting
L 06/11/2020 - 10:12:56: [SM]   [3] Call_Finish
L 06/11/2020 - 10:12:56: [SM]   [4] Line 486, materialadmin/native.sp::FireOnConfigSetting
L 06/11/2020 - 10:12:56: [SM]   [5] Line 1346, materialadmin/function.sp::VerifyServerID
L 06/11/2020 - 10:12:56: [SM]   [6] Line 88, materialadmin/config.sp::ReadConfig
L 06/11/2020 - 10:12:56: [SM]   [7] Line 283, materialadmin.sp::OnPluginStart
```
Сначала думал что проблема с стороны конфигов которые находятся в папке  materialadmin,но нет,скомпилил последнюю версию плагина которая на github,и заменил конфиги,ошибка осталась.
Плагин компилировал на последней версии sm.

В чем может быть проблема?

**Comment by MAGNAT2645** [comment]
Там же чётко сказано, что не найден натив [MAGetConfigSetting](https://github.com/SB-MaterialAdmin/NewServer/blob/master/addons/sourcemod/scripting/include/materialadmin.inc#L393).
Попробуй полностью переустановить все исходники с GitHub и перекомпилируй (особенно [materialadmin.sp](https://github.com/SB-MaterialAdmin/NewServer/blob/master/addons/sourcemod/scripting/materialadmin.sp) со всеми подскриптами в папке [materialadmin](https://github.com/SB-MaterialAdmin/NewServer/tree/master/addons/sourcemod/scripting/materialadmin) И [materialadmin.inc](https://github.com/SB-MaterialAdmin/NewServer/blob/master/addons/sourcemod/scripting/include/materialadmin.inc))

**Comment by GameFenix** [comment]
Я и компилил последнюю версию плагина с gihthub.
Скриншот materialadmin.inc который использовал: https://imgur.com/a/FnXBDUJ

**Comment by MAGNAT2645** [comment]
Тогда с какой целью перезагрузку плагина делаешь? Не все плагины рассчитаны на ручную перезагрузку (не добавляется поддержка для этого).
