### ISSUE TITLE
Админы без флага `e` могут снимать мут

### ISSUE THREAD

**Issue by OkyHp** [SB-MaterialAdmin/NewServer#13]
Наблюдаю такой баг/неисправность:
```
[MA] Trust no Bitch | 死んでく включил голосовой чат Defender.  
黒死病✟Trust no Bitch | 死んでください :  !unmute Defender
[MA] Добавлен в бд Defender.
```
При этом у админа нет флага на разбан (`e`)
Trust no Bitch | 死ん Kami res, admin, kick, ban, map, chat, vote, custom(1)
p.s. Я просто предполагаю, что скорее всего размут стоит на тот же флаг что и разбан*
Поправьте, если не прав. Команду !unban не проверял (Прошу прощение, тупанул немного).
Спасибо за внимание.

**Comment by CrazyHackGUT** [comment]
За размут отвечает веб-флаг разбана, вроде бы. Если не ошибаюсь.
@Grey-rus поправь, если не прав.

**Comment by Grey-rus** [comment]
Описание хоть читал? Там же ясно написано 
```
sm_ungag <#userid|#all|#ct|#t|#blue|#red> [reason] - ADMFLAG_CHAT - включение текстового  чата
sm_unmute <#userid|#all|#ct|#t|#blue|#red> [reason] - ADMFLAG_CHAT - включение голосового чата
sm_unsilence <#userid|#all|#ct|#t|#blue|#red> [reason] - ADMFLAG_CHAT - включение всего чата
```
И ещё нужны веб флаги (не путай срвер флаги) как при разбане.
В новой версии будет настройки использовать веб флаги или сервер флаги.
```
// Использование прав на размут и разбан
// 0 - можно всё при наличие серверных флагов без веб
// 1 - при наличие серверных и веб флагов
"UnMuteUnBan" "1"
```

**Comment by OkyHp** [comment]
Понял, прошу прощение за мою невнимательность
