### ISSUE TITLE
Как добавить админам муты?

### ISSUE THREAD

**Issue by Borzoff** [SB-MaterialAdmin/NewServer#139]
Здравствуйте, как дать админом возможность мутить?
`groups.cfg

{
	
	"Patroul"
	{
		"flags"		"bcdef"
		"immunity"		"50"
		"overrides"
		{
			"sm_burn"		"deny"
			"sm_drug"		"deny"
			"sm_unmute"		"allow"
			"sm_fire"		"deny"
			"sm_mute"		"allow"
			"sm_timebomb"		"deny"
			"sm_speed"		"deny"
			"sm_freeze"		"deny"
			"sm_slap"		"deny"
			"sm_ungag"		"allow"
			"sm_gag"		"allow"
		}
	}

`

**Comment by CrazyHackGUT** [comment]
А у них с такими оверрайдами прав на муты нет?

**Comment by Borzoff** [comment]
> А у них с такими оверрайдами прав на муты нет?

Нету

**Comment by CrazyHackGUT** [comment]
Как проверяется наличие прав? Через команду/админменю?

**Comment by Borzoff** [comment]
> Как проверяется наличие прав? Через команду/админменю?

Админ команду и через админ панель

**Comment by Borzoff** [comment]
Я обновил плагин муты работают, но через сайт не добавляются.
