### ISSUE TITLE
Не работает вообще админка 0.6.2

### ISSUE THREAD

**Issue by e-zhuravlev** [SB-MaterialAdmin/NewServer#14]
Обновил плагины и перевод но просто не подгружает админов а если использовать плагин ma_adminmenu то ругается что нет нужного плагина materialadmin.smx

**Comment by CrazyHackGUT** [comment]
Недостаточно информации.
Логи?

**Comment by e-zhuravlev** [comment]
класс я уже откатился.

**Comment by Grey-rus** [comment]
С какой версии было обновление?

**Comment by e-zhuravlev** [comment]
0.6.0

**Comment by Grey-rus** [comment]
Нужно полностью обновлять, и конфиг, какая версия см?

**Comment by e-zhuravlev** [comment]
ну версия SM 1.9 последняя + обновил все кроме .cfg

**Comment by Grey-rus** [comment]
Там добавились настройки касающийся с админкой

**Comment by e-zhuravlev** [comment]
спасибо за ответ попробую еще раз сначала)

**Comment by e-zhuravlev** [comment]
Спасибо! Обновил cfg и все ок!

**Comment by Grey-rus** [comment]
Это изменения были в 0.6.1 и там это писалось.
