### ISSUE TITLE
Spam in console

### ISSUE THREAD

**Issue by User1111111111111111111111** [SB-MaterialAdmin/NewServer#143]
L 02/25/2022 - 14:07:14: [materialadmin.smx] Checking ban for: STEAM_1:1:599371070. QUERY: SELECT a.`bid`, a.`length`, a.`created`, a.`reason`, b.`user` FROM `sb_bans` a LEFT JOIN `sb_admins` b ON a.`aid` = b.`aid` WHERE ((a.`type` = 0 AND a.`authid` REGEXP '^STEAM_[0-9]:1:599371070$') OR (a.`type` = 1 AND a.`ip` = '')) AND (a.`length` = 0 OR a.`ends` > UNIX_TIMESTAMP()) AND a.`RemoveType` IS NULL LIMIT 1
L 02/25/2022 - 14:07:14: [materialadmin.smx] ma_checker: OnClientAuthorized Query SELECT COUNT(bid) FROM `sb_bans` WHERE ((`type` = 0 AND `authid` REGEXP '^STEAM_[0-9]:1:599371070$') OR (`type` = 1 AND `ip` = '')) LIMIT 1
L 02/25/2022 - 14:07:14: [materialadmin.smx] DelOflineInfo:QUERY: DELETE FROM `offline` WHERE `auth` = 'STEAM_1:1:599371070'
L 02/25/2022 - 14:07:14: [materialadmin.smx] Check Mute: STEAM_1:1:599371070. QUERY: SELECT (c.`ends` - UNIX_TIMESTAMP()), c.`type`, c.`length`, c.`reason`, a.`authid` FROM `sb_comms` AS c LEFT JOIN `sb_admins` AS a ON a.`aid` = c.`aid` LEFT JOIN `sb_srvgroups` AS g ON g.`name` = a.`srv_group` WHERE `RemoveType` IS NULL AND c.`authid` REGEXP '^STEAM_[0-9]:1:599371070$' AND (`length` = 0 OR `ends` > UNIX_TIMESTAMP()) LIMIT 1
L 02/25/2022 - 14:07:14: [materialadmin.smx] CheckClientMute: set Bulka023 type 0
L 02/25/2022 - 14:07:24: [materialadmin.smx] OnClientPreAdminCheck(): Bulka023<41><> (in admincache updating cycle? No)
L 02/25/2022 - 14:07:24: [materialadmin.smx] OnClientPostAdminCheck(): Bulka023<41><> (in admincache updating cycle? No)

Can i somehow delete this? I don't want this spam in console....

**Comment by MAGNAT2645** [comment]
You can by disabling DEBUG and recompiling the plugin or/and by disabling `sv_logecho` (`sv_logecho 0`)
