### ISSUE TITLE
проблема с MA

### ISSUE THREAD

**Issue by koly600** [SB-MaterialAdmin/NewServer#144]
Дает такую ошибку при бане/муте игрока и на сайте нет списка банов мутов, есть ошибки в логах с бд связанныехотя все правильно сделал
[MA] Не получилось добавить в бд Добрый человек, операция записана в бекап, при возобновления соеденения данные занесутся в бд.
[sourcebans.log](https://github.com/SB-MaterialAdmin/NewServer/files/8412540/sourcebans.log)
[LogDateBase_20220404.log](https://github.com/SB-MaterialAdmin/NewServer/files/8412541/LogDateBase_20220404.log)
[errors_20220404.log](https://github.com/SB-MaterialAdmin/NewServer/files/8412542/errors_20220404.log)
[L20220404.log](https://github.com/SB-MaterialAdmin/NewServer/files/8412543/L20220404.log)
.

**Comment by CrazyHackGUT** [comment]
Так у Вас таблиц в базе нет. Что я-то сделаю?

**Comment by koly600** [comment]
> 

Есть

**Comment by CrazyHackGUT** [comment]
А плагин пишет, что ему база сказала, что таблиц нет. А информацию плагин получил от драйвера. А драйвер от базы.

Вы уверены, что таблицы есть?

**Comment by CrazyHackGUT** [comment]
Актуальность неизвестна, закрываю.
