### ISSUE TITLE
Добавить в список Офф бана и Админов

### ISSUE THREAD

**Issue by RRimmer** [SB-MaterialAdmin/NewServer#152]
Хотелось бы видеть и показ Админов которые вышли с сервера.
С учетом иммунитета естественно, если у одного админа 10 иммунитета а у другого 50, то он по прежнему будет показывается в офф бане, но забанить не сможет.

**Comment by CrazyHackGUT** [comment]
В следующий раз в правильном репо создавайте ишью сразу.

**Comment by CrazyHackGUT** [comment]
Вообще, оказывается, что в плагине уже есть настройка
https://github.com/SB-MaterialAdmin/NewServer/blob/03a671de19244b6be8a5ebf19971ac68c55f76e1/addons/sourcemod/configs/materialadmin/config.cfg#L277-L282

Запрошенные изменения точно требуются? Может Вы просто установите флаг `z` в значение? Тогда вноситься будут все, кроме рутов, но я сомневаюсь, что Вам жизненно необходимо банить оффлайново рутов.

**Comment by RRimmer** [comment]
Хмм, и вправду, я и забыл то что можно же просто флаг `z` поставить тогда думаю не надо.
