### ISSUE TITLE
[SM] У вас нет доступа к этой команде.

### ISSUE THREAD

**Issue by IIIef** [SB-MaterialAdmin/NewServer#18]
Всем привет, поставил сегодня новую версию, решил посмотреть, что изменилось. Так вот админы добавляться на сервер без проблем, раньше с этим была проблема, но сейчас сразу заметил другую проблему. В логах ошибок нет в конфиг админы добавлены, но админ не имеет доступа к командам. Если вручную прописать к примеру в admins_simple админа то да все работает. Как решить проблему?

**Comment by CrazyHackGUT** [comment]
Логи дебага давайте. Мы гадать тут не намерены. 
Если плагин без дебага скомпилирован, перекомпилируйте и дайте ему сутки поработать.

**Comment by IIIef** [comment]
Скомпилировал, но все чисто в логах. Попробуйте сами поставить и посмотрите, что у админа не будет прав хоть в конфиге admins и groups он прописан.

**Comment by IIIef** [comment]
Закинул сегодня плагин на сервер CSGO и о чудо, админка работает. Получается админка не работает на сервере TF2 точнее пишет нет доступа к sm_admin, но при этом меня через votemenu не забанить или замутить не могут. Сделайте пожалуйста, чтоб и на TF2 сервере тоже все работало. 
   И еще что заметил BasecommTime выставил на 60 минут вот так  "BasecommTime"		"60" и почему-то мутит навсегда, в чем проблема?

**Comment by IIIef** [comment]
С OldServer плагином проблем не было, а тут прям беда, навсегда мут дает)) https://forums.alliedmods.net/showthread.php?p=2097623

**Comment by Grey-rus** [comment]
Потому что надо настраивать кфг вашего плагина, он даёт мут через консольную команду. И там время не указано.

**Comment by IIIef** [comment]
В OldServer все настраивалось в SourceComms (DefaultTime) и там я выставлял к примеру на 60 минут и плагин выдавал мут или бан на 60 минут. В вашем плагине NewServer все настройки в materialadmin (BasecommTime) время для чего там настраивать тогда? 
   И вопрос насчет TF2 сервера так и открыт, почему админка не работает, а работает только на сервере CSGO.

**Comment by Grey-rus** [comment]
Ты хоть читать умеешь что я тебе пишу?

**Comment by IIIef** [comment]
Да понятно почему плагин такой кривой. Да хрен с этим плагином (Custom Votes), тема не про это, а про то, что ваш плагин не работает как я уже писал выше и вы это не прочитали видать, на серверах TF2 ваш плагин не работает.

**Comment by Grey-rus** [comment]
Плагин не кривой, просто нужно поднастроить. А почему не работает, смотрим логи.

**Comment by IIIef** [comment]
Логи емае пустые я это уже писал!

**Comment by Grey-rus** [comment]
включай дебаг плагина и логи плагина сюда.
MADEBUG 		1 в materialadmin.inc и компилируешь заново.

**Comment by IIIef** [comment]
Хорошо, щас так и сделаю.

**Comment by IIIef** [comment]
Все 5 логов скинуть или какой-то конкретно нужен?

**Comment by Grey-rus** [comment]
можешь все

**Comment by Grey-rus** [comment]
Про воте находишь это "command"		"sm_silence "{TARGET_ID}"" и меняешь на 
"command"		"sm_silence #"{TARGET_ID}" 60 votemute"

**Comment by IIIef** [comment]
спасибо с этим я потом посмотрю, что-то я не могу понять как сюда рар или зип скинуть

**Comment by IIIef** [comment]
[materialadmin.zip](https://github.com/SB-MaterialAdmin/NewServer/files/1692814/materialadmin.zip)

**Comment by Grey-rus** [comment]
Заливай на хостинг койни будь а сюда ссылку.

**Comment by Grey-rus** [comment]
Плагин работает, добавлен один админ Add Домовой (STEAM_0:1:15592217), и сюда по логам в меню заходил.

**Comment by IIIef** [comment]
да все правильно, но доступа нет к командам

**Comment by Grey-rus** [comment]
К каким командам нет доступа? по точнее.

**Comment by IIIef** [comment]
sm_admin

**Comment by IIIef** [comment]
на сервер csgo все работает, а на сервере tf2 нет

**Comment by CrazyHackGUT** [comment]
> на сервер csgo все работает, а на сервере tf2 нет

Дампаните админкеш. Команда `sm_dump_admcache`. Файл сюда скиньте.

**Comment by IIIef** [comment]
[admin_cache_dump.zip](https://github.com/SB-MaterialAdmin/NewServer/files/1692848/admin_cache_dump.zip)

**Comment by CrazyHackGUT** [comment]
В админкеше запись есть:
```
	/* num = 1, aid = 0x1A1, serialno = 0x1*/
	"Домовой"
	{
		"auth"			"steam"
		"identity"		"1:15592217"
		"flags"			""
		"immunity"		"100"
	}
```
Вопросы к SM. Плагин чисто сообщает СМу, кому надо выдавать админ-доступ, а он сам это обрабатывает.
Даже после перезахода на сервер нет админки?

**Comment by Grey-rus** [comment]
Странно по загрузке конфига флага нет `Load yes admin (name Домовой, auth steam, ident STEAM_0:1:15592217, flag 0, imuni 100, expire 0, max ban time -1, max mute time -1, web flag setings 1, web flag un ban mute 1)`

**Comment by IIIef** [comment]
Да, даже когда перезайду доступа нет

**Comment by Grey-rus** [comment]
скинь сюда файл с админами

**Comment by CrazyHackGUT** [comment]
У Вас группа админа как называется? Вы же через группу выдаёте админ доступ?

**Comment by IIIef** [comment]
Вот что заметил в дампе csgo есть  "flags"			"z" а в дампе tf2 нет  "flags"			""

**Comment by Grey-rus** [comment]
скинь сюда файл где записываются админы

**Comment by IIIef** [comment]
Вот дам с ксго где я и админы имеют доступ бес проблем[admin_cache_dump.zip](https://github.com/SB-MaterialAdmin/NewServer/files/1692854/admin_cache_dump.zip)

**Comment by IIIef** [comment]
[admins.zip](https://github.com/SB-MaterialAdmin/NewServer/files/1692856/admins.zip)

**Comment by CrazyHackGUT** [comment]
Как вариант, Вы выдали себе доступ только на CS:GO сервер, как и в TF2. А остальным не выдали на TF2.

**Comment by CrazyHackGUT** [comment]
KV выделяется:
```

**Comment by IIIef** [comment]
А зачем другим давать доступ на тф2, там доступ только мне к примеру нужен.

**Comment by Grey-rus** [comment]
В конфиге всё есть, баг какой то в чтение этого конфига.

**Comment by IIIef** [comment]
Как бы его исправить и я проверил не на одном сервере тф2 и на всех можно сказать одна проблема с админкой.

**Comment by Grey-rus** [comment]
Вобщем пока подожди, сам проведу такие тесты и узнаю где этот баг, когд загрузки этого конфига был взят из стандартного плагина см.

**Comment by IIIef** [comment]
Спасибо,  а можно еще решить проблему с мутами? https://github.com/SB-MaterialAdmin/NewServer/issues/19

**Comment by Grey-rus** [comment]
Баг при загрузке флага админу нашли, выложу в будущем, а про мут через веб это не так просто решить. Потому как веб не рассчитана на такое, а это я придумал для облегчения но вышло так всё.

**Comment by IIIef** [comment]
Спасибо.
