### ISSUE TITLE
Ошибки в MaterialAdmin

### ISSUE THREAD

**Issue by danyzinho** [SB-MaterialAdmin/NewServer#2]
Materialadmins.smx перестает работать после активного времени, просто перезагрузить сервер, чтобы вернуться к работе, но через некоторое время для работы. Моя ошибка, я вход этот отказ.

[SM] Blaming: materialadmin.smx
[SM] Call stack trace:
[SM] [1] Line 60, materialadmin/database.sp::ConnectBd
[SM] [2] Line 10, materialadmin/database.sp::MAConnectDB
[SM] [3] Line 262, C:\Users\grey\Desktop\scripting\materialadmin.sp::OnPluginStart
L 07/28/2017 - 15:53:52: [SM] Unable to load plugin "materialadmin.smx": Error detected in plugin startup (see error logs)

[materialadmin.smx] plugin version 0.5.7 beta
SM - 1.8 - build 6016
MM - 1.10 - build 959

простите мой русский переводчик =)

**Comment by CrazyHackGUT** [comment]
You use Google Translate?
I think, we can communicate with English Language.
All errors starts with "Exception reported". Can you show, which Exception message was there?

**Comment by danyzinho** [comment]
I'm Brazilian, I use google translator.
Sorry forgot full copy

"[SM] Exception reported: Script execution timed out"

**Comment by Grey-rus** [comment]
Попробуй увеличить тут "SlowScriptTimeout"	"8" файл настройки сорсмода core.cfg

**Comment by danyzinho** [comment]
Thanks, I increased the "SlowScriptTimeout" to 12, I am with the plugin on for 2 days without error.

**Comment by danyzinho** [comment]
Sorry but the problem happened again

[SM] Exception reported: Script execution timed out
[SM] Blaming: materialadmin.smx
[SM] Call stack trace:
[SM]   [1] Line 60, materialadmin/database.sp::ConnectBd
[SM]   [2] Line 10, materialadmin/database.sp::MAConnectDB
[SM]   [3] Line 262, C:\Users\grey\Desktop\scripting\materialadmin.sp::OnPluginStart
[SM] Unable to load plugin "materialadmin.smx": Error detected in plugin startup (see error logs)

**Comment by Grey-rus** [comment]
Просто плагин не смог за отведенное время подключится к бд(или завис при подключение к нему), вот его и см отключил.

**Comment by danyzinho** [comment]
Sorry did not understand

**Comment by Dreizehnt** [comment]
Danyzinho, connection time to the database has expired and plugin crashed or did not have time to connect, after which it was disabled by the SM core.
