### ISSUE TITLE
Question about Immunity

### ISSUE THREAD

**Issue by Master-GitHub** [SB-MaterialAdmin/NewServer#20]
Hello!

Admin can ban the other admin with the same Immunity level. Can it be changed or create some cvar to toggle it?

**Comment by CrazyHackGUT** [comment]
This is depends on SourceMod convar, `sm_immunity_mode`. From personal and group immunity SM takes higher.
Also if user have root access (`z`), he can ban/mute/gag/slap/slay/etc. any user. Root administrators ignores immunity.

**Comment by Master-GitHub** [comment]
Thanks for the explanation, but Can i change that admin with the same Immunity cant ban other admin?

For example i have group "Admin" with 40 Immunity level and admin X can ban admin Y.

**Comment by CrazyHackGUT** [comment]
You can.
Open `cfg/sourcemod/sourcemod.cfg` and read this carefully:
```
// Sets how SourceMod should check immunity levels when administrators target 
// each other.
// 0: Ignore immunity levels (except for specific group immunities).
// 1: Protect from admins of lower access only.
// 2: Protect from admins of equal to or lower access.
// 3: Same as 2, except admins with no immunity can affect each other.
// --
// Default: 1
sm_immunity_mode 1
```

If you don't understand this really nice description, just set `sm_immunity_mode` to value `2`.

**Comment by Master-GitHub** [comment]
Thank you very much for help.
