### ISSUE TITLE
Ошибки в логах

### ISSUE THREAD

**Issue by MaZaHaKa228** [SB-MaterialAdmin/NewServer#23]
Здравствуйте. При установке Material Admin пишет в логах такие ошибки:
L 03/28/2018 - 15:50:45: [SM] Unable to load plugin "materialadmin.smx": Native "Regex.Regex" was not found
L 03/28/2018 - 15:50:45: [SM] Unable to load plugin "ma_checker.smx": Could not find required plugin "materialadmin"

Как можно исправить?

**Comment by Grey-rus** [comment]
Версия сорсмода какая? Плагин тока для см 1.7 и выше.

**Comment by MaZaHaKa228** [comment]
1.9

**Comment by CrazyHackGUT** [comment]
Проверьте наличие расширения Regex в загруженных. Для этого используется команда `sm exts list`.

**Comment by MaZaHaKa228** [comment]
Он установлен и работает

**Comment by CrazyHackGUT** [comment]
Хорошо, версия какая у расширения?

**Comment by MaZaHaKa228** [comment]
Уже решил данный вопрос. Спасибо)
