### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by e-zhuravlev** [SB-MaterialAdmin/NewServer#25]
я обновил плагины и конфиг - сервер в краше

**Comment by CrazyHackGUT** [comment]
Может хотя бы ссылку на Accelerator приложите?

**Comment by e-zhuravlev** [comment]
ЕСТЬ дебаг лог

**Comment by CrazyHackGUT** [comment]
Если он в CS:GO не урезанный до жести - скидывай.

**Comment by e-zhuravlev** [comment]
((( урезанный

**Comment by CrazyHackGUT** [comment]
Тогда онли Асселератор.
Ничем помочь не можем.

**Comment by e-zhuravlev** [comment]
короче кидаю плагины с выключенным дебагом и новый кфг при запуске ругается на расширение с базой данных. Сейчас попробую вытащить с консоли

**Comment by e-zhuravlev** [comment]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./srcds_linux -game csgo -port 27039 +ip 31.28.168.219 -usercon +game_type 0 +g'.
Program terminated with signal 11, Segmentation fault.
#0  0xf75c07fa in vfprintf () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
#0  0xf75c07fa in vfprintf () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
End of Source crash report

**Comment by e-zhuravlev** [comment]
Ребята))) все уже ок

**Comment by Grey-rus** [comment]
На ксс проверял крашей не было, да и изменения не большие. Бд не трогал.

**Comment by e-zhuravlev** [comment]
это мой косяк.... у меня предложение. разделить на 2 конфига.  так как при смене нужно вносить свои причины и ID снова. может сделать один конфиг для причин и ID и тд а другой базовый чтоб просто можно было перезалить и если даже что-то измениться то не будет критично. + добавить несколько языков в причины бана.

**Comment by Grey-rus** [comment]
Подумаю на счёт разделением конфига.

**Comment by Grey-rus** [comment]
Сервер крашится при значение "AdminUpdateCache" "2" обновите плагин.
