### ISSUE TITLE
Спам ошибки запроса

### ISSUE THREAD

**Issue by MAGNAT2645** [SB-MaterialAdmin/NewServer#28]
MA 0.3.4 beta (я понимаю, что версия довольно старая, но стабильная)

В materialadmin.log постоянно спамит:
[materialadmin.smx] CheckCallbackBekap: Column count doesn't match value count at row 1

EDIT: Это из локальной maDatabase.sq3.
Я так понимаю, проблема заключается в хранимой query.
Например,
**INSERT INTO sb_bans (type, ip, name, created, ends, length, reason, aid, adminIp, sid, country) VALUES (0, '176.118.11.222', UNIX_TIMESTAMP(), UNIX_TIMESTAMP() + 60, 60, 'Spam Connecting', 0, '95.46.114.132', 1, ' ')**
Здесь проблема заключается в том, что к name присваивается UNIX_TIMESTAMP()

**Comment by CrazyHackGUT** [comment]
Старые версии Серый навряд ли поддерживать будет. Лучше обновитесь.

**Comment by Grey-rus** [comment]
запрос не верный и всё нужно подправить, а то что вы говорите что она стабильная, вы не знаете какие там баги есть.

**Comment by MAGNAT2645** [comment]
Баги там есть, не отрицаю, но это самая последняя версия из общего релиза (архив со старым SM 1.6 + новый синтакс для SM 1.7 + Веб часть).

Если я буду обновлять серверную часть (плагины), то это не повлияет на Веб (у меня версия из последнего вашего релиза 1.1.5.4)?

Я только щас понял, что новые версии плагинов позволяют вернуть basecomm для SourceMod. Нужно ли мне заменять basecomm.smx на ma_basecomm и adminmenu.smx на ma_adminmenu?

**Comment by MAGNAT2645** [comment]
Проблема была решена ещё в мае, поэтому можно закрыть эту тему.
