### ISSUE TITLE
[BUG] IgnoreBanServer [1] | Не пашет игнор Банов.

### ISSUE THREAD

**Issue by BlackYuzia** [SB-MaterialAdmin/NewServer#3]
@Grey-rus 
Тестил я тут:
Игнор банов на веб и других серверах.
установил cvаr:
> 		"IgnoreBanServer"	"1"
Чет не пашет.
Если бан на сервере №1 то на №2 не трогает.
НО веб вроде должен на всех работать. 
Но хрен там :D
Пруфы:
![2](https://user-images.githubusercontent.com/25010528/28755291-08b6d4ee-7560-11e7-9fe7-61199537d919.png)
![default](https://user-images.githubusercontent.com/25010528/28755293-0b8e4d50-7560-11e7-9008-5765d1baf06d.png)

PS: Хоть и ники разные. SteamID одинаковый :3

**Comment by Grey-rus** [comment]
// 0 - выключено
// 1 - тока с серера
// 2 - с сервера и веб
Незабываем обновлять и конфиг.

**Comment by BlackYuzia** [comment]
@Grey-rus  Вот мой кфг:

**Comment by BlackYuzia** [comment]
@Grey-rus Вот мой КФГ:
[materialadmin.zip](https://github.com/SB-MaterialAdmin/NewServer/files/1190305/materialadmin.zip)

**Comment by BlackYuzia** [comment]
@Grey-rus Я понял что там есть 0,1,2.
просто если 2 то это блок и Веб и Сервера верно?
А если 1 то сервы но Веб Банит на всех?
(если все правильно)

**Comment by Grey-rus** [comment]
0 это на все сервера, 1 тока на этом сервере, 2 на этом и веб.

**Comment by BlackYuzia** [comment]
@Grey-rus так вот. при кваре = 1.
все супер. Но веб пускает. т.е. с веб не банит на всех.
или ставить 2 что бы веб на всех работал?

**Comment by Grey-rus** [comment]
2 ставь

**Comment by BlackYuzia** [comment]
@Grey-rus Не помогло

**Comment by Grey-rus** [comment]
Проверю на днях, может ошибка в запросе.
