### ISSUE TITLE
No acces to sm_ban

### ISSUE THREAD

**Issue by Master-GitHub** [SB-MaterialAdmin/NewServer#39]
Noone can ban with command even with flag z:

`sm_ban Master 1 test
[MA] Usage: No Access to #all|#ct|#t|#blue|#red
[MA] Usage: sm_ban <#userid|#all|#ct|#t|#blue|#red> <time> [reason]`

Ban through menu works well.

MaterialAdmin version: 0.7.7
Sourcemod version: 1.9.0.6265

My config: https://hastebin.com/ketijocoya.php

The problem appeared after the update from 0.7.6 to 0.7.7

**Comment by Grey-rus** [comment]
config "MassBan"  to 2

**Comment by Master-GitHub** [comment]
@Grey-rus Thanks
