### ISSUE TITLE
Не добавляются админы через вэб.

### ISSUE THREAD

**Issue by IIIef** [SB-MaterialAdmin/NewServer#4]
Не в одной из бэт не работает добавление админов в конфиг сервера. Единственное где работает добавление моментально это в релизе 1154 Old_serverside_(1.5.3-1.8). Когда запускаю сервер то админы которые были прописаны в вэбке они конечно добавляются, но если удалить одного или всех, то они так и будут находиться в конфиге.

**Comment by BlackYuzia** [comment]
@IIIef есть подозрение что у тебя в БД нет одной таблицы.
Спроси у @CrazyHackGUT / @Grey-rus  по этому поводу.

а так то попробуй это провернуть в SQL запросе:
Выполнить запрос к Базе данных, 
ALTER TABLE `sb_srvgroups` ADD `maxbantime` INT NOT NULL default -1, ADD `maxmutetime` INT NOT NULL default -1;

**Comment by BlackYuzia** [comment]
Если ты про "моментальное" то в ВЕБ надо вырубить слияние с олд. плагином.

**Comment by IIIef** [comment]
Слияние есть, галочка стоит) А вот запрос сделал ALTER TABLE sb_srvgroups ADD maxbantime INT NOT NULL default -1, ADD maxmutetime INT NOT NULL default -1; и результат такой
Ответ MySQL: Документация

#1060 - Duplicate column name 'maxbantime'

хз че за запрос.

Короче если запустить сервак на бето плагинах, то админы добавляются, но если потом произвести какие-то действия с админами, то ничего не будет меняться в конфиге сервака.

**Comment by Grey-rus** [comment]
Ответ означает что у тебе этот запрос не нужно делать было, у тебя всё есть, а что что сразу не обновляется, просто веб не шлёт команду обновить админов, обнови ручками через меню или через команду.

**Comment by CrazyHackGUT** [comment]
Запрос с веба не отправляется только если в опциях веб-части включена совместимость с плагинами SourceBans.

**Comment by IIIef** [comment]
Я правильно понимаю, что если включена совместимость, то бэта не будет нормально работать? Если да, то тогда зачем эта совместимость, что-то не пойму)

**Comment by CrazyHackGUT** [comment]
@IIIef совместимость для SourceBans плагинов (старых плагинов, если всё ещё не ясно), из названия же ясно.
Если она включена, то веб-панель отправляет команды, как будто на серверах стоит четыре плагина (sbpp\_main, sbpp\_comms и т.д.).
Если она выключена, то веб-панель отправляет команды для своего плагина Material Admin.

Всё просто.

**Comment by IIIef** [comment]
Спасибо, что разжевали)))

**Comment by CrazyHackGUT** [comment]
Так проблема решена, или нет?

**Comment by IIIef** [comment]
Еще не проверял, сейчас на тестовом серваке проверю, но думаю в этом и была вся проблема.

**Comment by IIIef** [comment]
Нет, админы не добавляются и не удаляются. С включенной галкой совместимости происходит хоть какие-то действия в консоли сервера и да забыл написать еще и команда не известная для сервера в консоли появляется вовремя добавления и удаления админа Unknown command "sm_rehash"
В логе сервера есть запись L 08/03/2017 - 22:23:35: [basecommands.smx] "Console<0><Console><Console>" refreshed the admin cache. но админов нет) С выключенной галкой в сервере нет ни чего.

**Comment by BlackYuzia** [comment]
@IIIef вроде в новой там ma_rehash

**Comment by IIIef** [comment]
Ну так я бэту скачал 0.5.8. Неужели только у меня на бэте такое?

**Comment by IIIef** [comment]
Короче с выключенной совместимостью плагин отправляет команду ma_wb_rehashadm только на удаление админов, а вот на добавление админа вэбка не отправляет ma_wb_rehashadm. Получается косяк вэбки, как это исправить?

**Comment by Grey-rus** [comment]
Напиши в дискорде https://discord.gg/RVQJKaV.
