### ISSUE TITLE
Краш VerifyBan

### ISSUE THREAD

**Issue by kleuser75** [SB-MaterialAdmin/NewServer#45]
Крашит сервер
Стоит акселератор+сошка от феникса, увидел строчку
**materialadmin.smx::VerifyBan** на эту функцию ссылается эта краш лог.
https://throttle.zizt.ru/kggg7pmfnsfe
[crash_kggg7pmfnsfe.zip](https://github.com/SB-MaterialAdmin/NewServer/files/2726635/crash_kggg7pmfnsfe.zip)

MA 0.7.7

**Comment by CrazyHackGUT** [comment]
Хз, кстати, в актуальности данного Issue. Вроде исправлял. Надо проверить.

**Comment by CrazyHackGUT** [comment]
Исправлено таки?

**Comment by kleuser75** [comment]
Вроде как да. Крашей пока нет на последних версиях.
