### ISSUE TITLE
Критическая ошибка в новой версии

### ISSUE THREAD

**Issue by megoRU** [SB-MaterialAdmin/NewServer#51]
L 05/04/2019 - 21:44:02: [materialadmin.smx] "Console<0><Console><Console>"  banned "dang1e (STEAM_1:1:****** IP_IP HIDDEN)" (minutes "129600") (reason "*********")
Dropped dang1e from server: Забанен админом: *****
Причина: *******
Бан выдан: 05/04/2019 - 21:44:02
Забанен на: 90 дн.
Подробнее на сайте: 
L 05/04/2019 - 21:44:02: [materialadmin.smx] CreateBdCallback Query Failed: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '\'IP HIDDEN\' AND `port` = \'27015\' LIMIT 1), 0)) WHERE (a.authid REGEXP \'' at line 1

**Comment by megoRU** [comment]
Баны не записываются в БД

**Comment by megoRU** [comment]
@CrazyHackGUT ................

**Comment by megoRU** [comment]
https://github.com/SB-MaterialAdmin/NewServer/commit/d2d22b7e833d3d5bd835c49eae179e1ef7216d89

**Comment by CrazyHackGUT** [comment]
Не хотел закрывать.
Проверьте теперь.

**Comment by megoRU** [comment]
исправлено.

**Comment by CrazyHackGUT** [comment]
Пересобрал бинарник в репозитории.

https://github.com/SB-MaterialAdmin/NewServer/commit/474d53b01063fdbee9debbe75289eb57a6199666
