### ISSUE TITLE
SQL Query Error (ыыы)

### ISSUE THREAD

**Issue by megoRU** [SB-MaterialAdmin/NewServer#54]
L 06/01/2019 - 18:10:18: [materialadmin.smx] SQL_CheckCallbackReport Query Failed: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '\'****ip hidden****\' AND `port` = \'27015\' LIMIT 1), 0), 'заебал болта' at line 1

**Comment by megoRU** [comment]
Sasuke: есть команда !report (писал челик до бага этого)
мб это поможет. я так понял что то пошло не так.

**Comment by CrazyHackGUT** [comment]
За такие информативные заголовки скоро бить палками начну.
Нет бы просто написать "SQL Query Error".

**Comment by CrazyHackGUT** [comment]
Проверяйте.

**Comment by CrazyHackGUT** [comment]
Результаты теста? Исправлено?

**Comment by megoRU** [comment]
исправлено
