### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by sa32qpe** [SB-MaterialAdmin/NewServer#64]
L 07/17/2019 - 20:42:00: [SM] Exception reported: No current result set
L 07/17/2019 - 20:42:00: [SM] Blaming: materialadmin.smx
L 07/17/2019 - 20:42:00: [SM] Call stack trace:
L 07/17/2019 - 20:42:00: [SM]   [0] DBResultSet.FetchRow
L 07/17/2019 - 20:42:00: [SM]   [1] Line 1173, materialadmin/database.sp::VerifyBan
L 07/17/2019 - 20:42:30: [SM] Exception reported: Script execution timed out
L 07/17/2019 - 20:43:00: [SM] Exception reported: Script execution timed out
L 07/17/2019 - 21:13:02: Error log file session closed.

v 0.7.6

**Comment by sa32qpe** [comment]
> L 07/17/2019 - 20:42:00: [SM] Exception reported: No current result set
> L 07/17/2019 - 20:42:00: [SM] Blaming: materialadmin.smx
> L 07/17/2019 - 20:42:00: [SM] Call stack trace:
> L 07/17/2019 - 20:42:00: [SM] [0] DBResultSet.FetchRow
> L 07/17/2019 - 20:42:00: [SM] [1] Line 1173, materialadmin/database.sp::VerifyBan
> L 07/17/2019 - 20:42:30: [SM] Exception reported: Script execution timed out
> L 07/17/2019 - 20:43:00: [SM] Exception reported: Script execution timed out
> L 07/17/2019 - 21:13:02: Error log file session closed.
> 
> версия 0.7.6

**Comment by CrazyHackGUT** [comment]
Так актуально или нет? В связи с чем был закрыт Issue?
Второе посмотрю.

**Comment by CrazyHackGUT** [comment]
Увидел новое Issue
Лучше было бы это оставить касательно `No current result set`, а проблему с `ArrayList` в отдельное вынести, да.

**Comment by sa32qpe** [comment]
Мисс клик , случайно кликнул не туда закрыл. Там вторую закроете пожалуйста, я создал две получается, после того как закрыл эту

**Comment by sa32qpe** [comment]
+ это еще забыл добавить на v 0.7,8

L 07/18/2019 - 19:48:52: [SM] Exception reported: Invalid index 0 (count: 0)
L 07/18/2019 - 19:48:52: [SM] Blaming: materialadmin.smx
L 07/18/2019 - 19:48:52: [SM] Call stack trace:
L 07/18/2019 - 19:48:52: [SM] [0] ArrayList.Get
L 07/18/2019 - 19:48:52: [SM] [1] Line 974, materialadmin/menu.sp::ShowInfoMuteMenu
L 07/18/2019 - 19:48:52: [SM] [2] Line 375, materialadmin/database.sp::SQL_Callback_GetInfoMute
L 07/18/2019 - 20:21:04: Error log file session closed.

**Comment by sa32qpe** [comment]
Можно закрывать? Вы сможете решить проблему?

**Comment by megoRU** [comment]
@CrazyHackGUT ыыы

**Comment by CrazyHackGUT** [comment]
Суть Issues не в том, чтобы просто оповестить разработчиков о проблеме и закрыть. Их суть - в том, чтобы видеть список конкретных проблем, которые нужно исправлять.
Исправлениями в любом случае раньше выходных я заняться не смогу (работаю). Исправить смогу. Закрывать - не надо.

В следующий раз, на каждую отдельную ошибку заводим отдельный Issue, пожалуйста. Тут две проблемы, которые никак не связаны между собой, а потому лучше всего делать именно так.
Другое второе Issue я обратно открыл, его закрывать не надо.

**Comment by CrazyHackGUT** [comment]
Комментарий отредактировал, убрал упоминание второй проблемы в связи с #65

**Comment by CrazyHackGUT** [comment]
Пора заняться этим.

**Comment by CrazyHackGUT** [comment]
Не проверял, должно помочь.
Вообще, ошибки подобного плана (с базой) всегда странными были.
