### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by sa32qpe** [SB-MaterialAdmin/NewServer#65]
L 07/18/2019 - 19:48:52: [SM] Exception reported: Invalid index 0 (count: 0)
L 07/18/2019 - 19:48:52: [SM] Blaming: materialadmin.smx
L 07/18/2019 - 19:48:52: [SM] Call stack trace:
L 07/18/2019 - 19:48:52: [SM]   [0] ArrayList.Get
L 07/18/2019 - 19:48:52: [SM]   [1] Line 974, materialadmin/menu.sp::ShowInfoMuteMenu
L 07/18/2019 - 19:48:52: [SM]   [2] Line 375, materialadmin/database.sp::SQL_Callback_GetInfoMute
L 07/18/2019 - 20:21:04: Error log file session closed.

**Comment by CrazyHackGUT** [comment]
Очередная странная проблема.
При каких условиях проявляется - непонятно. Будто админ в ожидании результата из базы снова открыл меню для выбора игроков.
Вроде теперь должно быть исправлено.
