### ISSUE TITLE
gamecms help

### ISSUE THREAD

**Issue by Dancbeunny98** [SB-MaterialAdmin/NewServer#66]
Подскажите пожалуйста как подключить данный плагин с банами к  game cms
![image](https://user-images.githubusercontent.com/37336183/63798891-91409080-c913-11e9-9c4e-8f28f8fd3113.png)

**Comment by CrazyHackGUT** [comment]
Необходимо установить веб-панель Material Admin как обычно. Сам плагин никакие таблицы в базе не создаёт. Инструкция по установке панели есть на HLmod.

По итогу, и плагин, и GameCMS необходимо будет подключить к одной и той же базе.

**P.S.**: Подобного характера вопрос можно (и нужно) было задавать либо на вышеупомянутом форуме, либо в официальном чате [GameCMS](https://t.me/gamecms) / Material Admin.

**Comment by Dancbeunny98** [comment]
> Необходимо установить веб-панель Material Admin как обычно. Сам плагин никакие таблицы в базе не создаёт. Инструкция по установке панели есть на HLmod.
> 
> По итогу, и плагин, и GameCMS необходимо будет подключить к одной и той же базе.
> 
> **P.S.**: Подобного характера вопрос можно (и нужно) было задавать либо на вышеупомянутом форуме, либо в официальном чате [GameCMS](https://t.me/gamecms) / Material Admin.

Спасибо. Так и сделал.
