### ISSUE TITLE
Кодировка против лагов 

### ISSUE THREAD

**Issue by hearest** [SB-MaterialAdmin/NewServer#67]
Прошу внести настройку, которая бы отменяла проверку кодировки, для исключения фризов. 
До этого делали сборку совместно:
[NewServer-master+off-debug+fix-lag-db.zip](https://github.com/SB-MaterialAdmin/Web/files/3562470/NewServer-master%2Boff-debug%2Bfix-lag-db.zip)

**Comment by hearest** [comment]
По возможности, реализация функции для снятия мута, гага, сайлента, бана по флагам. 
прописать в overrides, к примеру: "sm_unsilence" "z" или 	"sm_unmute"	"z" сейчас не даст результата

**Comment by CrazyHackGUT** [comment]
Под это дело советую завести отдельное Issue. Одна проблема/пожелание - одно Issue. Так проще держать список задач.

**Comment by CrazyHackGUT** [comment]
Проверьте теперь. В конфигурационном файле появился новый параметр `UseDatabaseFix`, который необходимо перевести в значение `0` для отключения фикса.

**Comment by megoRU** [comment]
@CrazyHackGUT админки не работают. Нет доступа. кеш админов не помогает

**Comment by megoRU** [comment]
скомпилировал его версию все работает

**Comment by CrazyHackGUT** [comment]
Нужно скомпилировать плагин с отладкой для получения большего кол-ва деталей о проблеме.

**Comment by megoRU** [comment]
хорошо будет время сделаю

**Comment by megoRU** [comment]
@CrazyHackGUT как дебаг то сделать?
#define DEBUG чот не работает...

**Comment by CrazyHackGUT** [comment]
https://github.com/SB-MaterialAdmin/NewServer/blob/master/addons/sourcemod/scripting/include/materialadmin.inc#L34
На единицу.

**Comment by CrazyHackGUT** [comment]
Беру на сегодня в план. Ожидаю либо до обеда каких-либо логов, чтобы можно было что-то курить, либо доступы.

**Comment by CrazyHackGUT** [comment]
Создал отдельную иссуйку. Любые логи или заметки по админкам - туда.
