### ISSUE TITLE
[Вопрос] SourceSleuth

### ISSUE THREAD

**Issue by Medium553** [SB-MaterialAdmin/NewServer#7]
В новой серверной части есть функционал SourceSleuth ? Просто не заметил ни слова в настройках, да и люди заходить с других акков начали, после перехода на МА. Если нет, будет ли он или что-то наподобие?

**Comment by rsgua** [comment]
Зачем он тебе? Он не коректно работает...

**Comment by Grey-rus** [comment]
В последней версии он добавлен, смотреть в конфиге.
