### ISSUE TITLE
Незагружающиеся админы

### ISSUE THREAD

**Issue by CrazyHackGUT** [SB-MaterialAdmin/NewServer#70]
При решении проблемы, описанной в #67, возникла другая проблема: админки перестали грузиться.

**Comment by megoRU** [comment]
Крч вам нужны логи, вы их получите.

**Comment by megoRU** [comment]
чот логи не пишуться.

**Comment by CrazyHackGUT** [comment]
Вроде как исправилось. Так что можно и закрывать 🤔

**Comment by OkyHp** [comment]
НИХУЯ!

**Comment by OkyHp** [comment]
Нет ни ошибок ничего. Соединение с БД установлено.

**Comment by OkyHp** [comment]
Проблема в этом коммите: https://github.com/SB-MaterialAdmin/NewServer/commit/ae43c8782f19d0a4f4892fe5654400d71f66ebf4

**Comment by OkyHp** [comment]
Сорян, все в порядке, я аутист)
