### ISSUE TITLE
Не работаю вышедшие игроки

### ISSUE THREAD

**Issue by theelsaud** [SB-MaterialAdmin/NewServer#73]
![image](https://user-images.githubusercontent.com/29007593/65359095-20378480-dc04-11e9-9fe5-3021659b7d29.png)
С этого коммита перестал работать раздел вышедшие игроки.
https://github.com/SB-MaterialAdmin/NewServer/commit/63ba143a3006a2fff7e84028a627c17c1ce5e9ab

**Comment by megoRU** [comment]
![image](https://user-images.githubusercontent.com/23276305/65359374-f894ec00-dc04-11e9-8770-19fec34df8bb.png)

есть же новее. но я тебя понял. Щаз проверю на своем сервере. Жди)

**Comment by CrazyHackGUT** [comment]
Скажите, пожалуйста, что конфиг Вы забыли обновить.

**Comment by megoRU** [comment]
![image](https://user-images.githubusercontent.com/23276305/65359439-2712c700-dc05-11e9-92a6-e348eca143d0.png)
Не воспроизвелось

**Comment by theelsaud** [comment]
> Скажите, пожалуйста, что конфиг Вы забыли обновить.

"IgnoreFlagOfflineBan"	"d"
Забыл добавить действительно)

**Comment by theelsaud** [comment]
Можно закрывать, мой косяк)
