### ISSUE TITLE
Баг с выдачей бана, после мута

### ISSUE THREAD

**Issue by theelsaud** [SB-MaterialAdmin/NewServer#76]
`
L 09/27/2019 - 19:43:28: [SM] Exception reported: Invalid database Handle 0 (error: 4)

L 09/27/2019 - 19:43:28: [SM] Blaming: materialadmin.smx

L 09/27/2019 - 19:43:28: [SM] Call stack trace:

L 09/27/2019 - 19:43:28: [SM]   [0] Database.Format

L 09/27/2019 - 19:43:28: [SM]   [1] Line 661, materialadmin/database.sp::CreateDB

L 09/27/2019 - 19:43:28: [SM]   [2] Line 533, materialadmin/database.sp::DoCreateDB

L 09/27/2019 - 19:43:28: [SM]   [3] Line 556, materialadmin/function.sp::GetClientToBd

L 09/27/2019 - 19:43:28: [SM]   [4] Line 863, materialadmin/menu.sp::OnlineClientSet

L 09/27/2019 - 19:43:28: [SM]   [5] Line 787, materialadmin/menu.sp::MenuHandler_MenuBReason
`

**Comment by theelsaud** [comment]
Sourcemod шалит?

**Comment by theelsaud** [comment]
А все, проблема из-за баз. Не были доступны так как beget лёг.

**Comment by megoRU** [comment]
а говорили багет топ!

**Comment by CrazyHackGUT** [comment]
Ну, в общем-то, с любым хостингом случается.

**Comment by theelsaud** [comment]
Kruzya, можешь кинуть свой дс сервер, а то у меня дискорд когда поддержка поломала, сервера не восстановила.

**Comment by CrazyHackGUT** [comment]
https://discord.io/kruzya
