### ISSUE TITLE
Наказания

### ISSUE THREAD

**Issue by IIIef** [SB-MaterialAdmin/NewServer#8]
Добрый день, в новую версию добавили просмотр наказаний? В старой версии в меню на сервере можно посмотреть отключенные микрофоны и чаты. Так же в этом меню можно посмотреть за что и когда выдан мут и когда он будет снят. А в новой версии такая возможность есть? Если нет, то добавьте пожалуйста, надеюсь это возможно.

**Comment by Grey-rus** [comment]
Нет такого и думаю не добавлю.

**Comment by CrazyHackGUT** [comment]
Модулем можно, кмк.
Раз @Grey-rus не хочет, можно попросить кого-нибудь из community сделать.

**Comment by IIIef** [comment]
Спасибо, что добавили.
