### ISSUE TITLE
VerifyMute BlessRNG

### ISSUE THREAD

**Issue by hearest** [SB-MaterialAdmin/NewServer#83]
Обновил MA 
Версия  "Material Admin" (0.7.9)
SourceMod Version: 1.11.0.6473
Metamod:Source version 1.11.0-dev+1128

Ошибка:
```
L 12/14/2019 - 13:18:59: [SM] Exception reported: Instruction contained invalid parameter
L 12/14/2019 - 13:18:59: [SM] Blaming: materialadmin.smx
L 12/14/2019 - 13:18:59: [SM] Call stack trace:
L 12/14/2019 - 13:18:59: [SM]   [1] Line 1297, materialadmin/database.sp::VerifyMute
```

Памагите BelssRNG

**Comment by CrazyHackGUT** [comment]
Попробуйте билд для SM 1.10.
Писали про это уже на HLmod. Похоже больше на баг компилятора от 1.11, и соответствующий Issue уже заведён (но пока ноль реакции).
https://github.com/alliedmodders/sourcepawn/issues/432

**Comment by hearest** [comment]
Можно тебя попросить с MADEBUG "1" компьльнуть? у самого нет возможности

**Comment by CrazyHackGUT** [comment]
Есть автобилды. И там есть вместе с дебагом.
https://builds.kruzya.me/SB-MaterialAdmin/NewServer/

**Comment by CrazyHackGUT** [comment]
Вроде как исправили. Закрываю.
