### ISSUE TITLE
Опять микрофризы из-за кодировки

### ISSUE THREAD

**Issue by kleuser75** [SB-MaterialAdmin/NewServer#89]
Опять были замечены микрофризы когда кто-то подключается к серверу.
Что опять не так? SM 1.10 же уже умеет работать с кодировкой utf8mb4.
Версия плагина 0.7.9 (перекомпелил даже на всякий случай сегодня на последнем билде 6460)

**Comment by CrazyHackGUT** [comment]
Сервер теряет соединение с БД, в следствии плагин переустанавливает принудительно кодировку.
В конфиге параметр есть, выключающий это поведение. Но возможны проблемы с кириллицей, если коннект действительно рвётся.

**Comment by kleuser75** [comment]
Коннект не теряется, всё работает нормально же.
Где этот параметр в конфиге, не по глазам что-то.

**Comment by CrazyHackGUT** [comment]
https://github.com/SB-MaterialAdmin/NewServer/blob/1b7f0aa34df7a87bd976543d9abaa39279eadbe4/addons/sourcemod/configs/materialadmin/config.cfg#L284-L289

**Comment by kleuser75** [comment]
Странно, как может терятся соединение если всё работает, баны вносятся, админы загружаются, я сам к базе подключаюсь без проблем... Можно ли как-то проверить, теряется соединение действительно или нет ?

**Comment by CrazyHackGUT** [comment]
К сожалению, никак.
Особенность драйверов БД SM в том, что они постоянно держат соединение. У MySQL есть настройка, которая такие "соединения" может убивать по таймауту бездействия, к примеру.

**Comment by kleuser75** [comment]
Ясно.
Ну вообщем отключение UseDatabaseFix проблему вроде бы решило.
