### ISSUE TITLE
Отсутствие команды (MUTE)

### ISSUE THREAD

**Issue by Jenyor** [SB-MaterialAdmin/NewServer#90]
Команда "ma_wb_block", заявленная в файле "[описание](https://github.com/SB-MaterialAdmin/NewServer/blob/95169441a140cdcc8c4baebb336a6f34b1f3d0d2/%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5.txt#L45)" не фигурирует в плагине, как следствие - не работает.
Как можно починить муты веба?

**Comment by megoRU** [comment]
Кстати да

**Comment by Jenyor** [comment]
Фиксанул самостоятельно.

**Comment by megoRU** [comment]
@CrazyHackGUT Ну это бан
