### ISSUE TITLE
Точка в конце сайта при бане

### ISSUE THREAD

**Issue by e-zhuravlev** [SB-MaterialAdmin/NewServer#91]
Проверил файл перевода и конфиг там точки у меня нет хотя выводит ее после сайта

**Comment by e-zhuravlev** [comment]
![photo_2020-02-12_21-00-44](https://user-images.githubusercontent.com/35569496/74377047-e140e000-4deb-11ea-9f6d-560e3c1506af.jpg)

**Comment by e-zhuravlev** [comment]
Сбивает игроков. Мелочь а не приятно

**Comment by CrazyHackGUT** [comment]
Писал же уже где-то, что точку добавляет сам движок игры, и с этим ничего не сделать.

**Comment by e-zhuravlev** [comment]
Жесть..

**Comment by CrazyHackGUT** [comment]
Ну как вариант могу лишь переместить сам адрес сайта в переводах повыше, чтобы точка была в конце времени бана, к примеру.
